### ISSUE TITLE
Broken example server urls in README.md

### ISSUE THREAD

**Issue by edmondb** [hapi-server/server-nodejs#37]
As I was working through some of the server setup examples, I noticed that the [Exmaple0 link](https://github.com/hapi-server/server-nodejs/blob/31b6e7690736838886a727cd664b85937480c76c/README.md?plain=1#L125) and the [Example 2 link](https://github.com/hapi-server/server-nodejs/blob/31b6e7690736838886a727cd664b85937480c76c/README.md?plain=1#L159) that reference the hapi-server.org/servers/ url don't actually work. They just return the following:

Invalid URL. See [start page](https://hapi-server.org/)

I suspect, you are missing `?url=http://hapi-server.org/servers/` in the links?

**Comment by rweigel** [comment]
Thanks for reporting!
