### ISSUE TITLE
PYTHONEXE is not treated well

### ISSUE THREAD

**Issue by dgarciabriseno** [hapi-server/server-nodejs#49]
I'm working on setting this up with a python exe managed by conda.

The README/code around PYTHONEXE is out of date. README says you can pass it in as an environment variable, but that doesn't work. It has to be passed in as `--python path/to/python`

The other issue is the file check for the catalog. I'm using python to generate info. So my catalog looks like this

```json
"catalog": [
    {
      "id": "EIT_171",
      "title": "SOHO instrument EIT, measurement 171.",
      "info": "$PYTHONEXE $HAPISERVERPATH/src/id.py --id EIT_171"
    }
]
```

This check [here](https://github.com/hapi-server/server-nodejs/blob/cea632de2c12ddf201e8a5f35bc3f9d545df594b/lib/metadata.js#L435C79-L435C80) is trying to parse my command as a json file.

With the `split[0]` it grabs the python binary, which exists, and so the code takes the file path even though I want it to take the command path.

**Comment by rweigel** [comment]
Thanks for the detailed report. 

Partially tested fix for PYTHONEXE in https://github.com/hapi-server/server-nodejs/tree/49-pythonexe-is-not-treated-well

Should have fix for other issue soon.

**Comment by rweigel** [comment]
getting closer
