### ISSUE TITLE
QinDenton improvement

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-nodejs#6]
Need a Python function that downloads

http://mag.gmu.edu/ftp/QinDenton/hour/merged/latest/WGhour-latest.d.zip

extracts it to disk (w/o reading file into memory) and reads unzipped file and splits it into files by year, e.g. WGhour-latest-2000.d, WGhour-latest-2001.d, ... All lines starting with 2000 go into WGhour-latest-2000.d, etc.

Need to do the same for http://mag.gmu.edu/ftp/QinDenton/5min/merged/latest/WGparameters5min-latest.d.zip. In this case, file are by month, e.g., WGparameters5min-latest-200011.d, WGparameters5min-latest-200012.d, etc.

Function definition should be
```
def qindenton_dl(dir, res=[hour|5min]):
```

**Comment by rweigel** [comment]
Records are actually uniform, so only need to seek to a line and seek distance can be computed.

**Comment by hbatta** [comment]
`
import os.path
import zipfile
import requests
import pandas as pd


# def qindenton_dl(dir, res=[hour|5min]):
def qindenton_dl(dir, res):
    # url = 'http://mag.gmu.edu/ftp/QinDenton/hour/merged/latest/WGhour-latest.d.zip'
    url = 'http://mag.gmu.edu/ftp/QinDenton/5min/merged/latest/WGparameters5min-latest.d.zip'

    file_path = dir + url.split("/")[-1]

    chunk_size = 128
    r = requests.get(url, stream=True)
    with open(file_path, 'wb') as fd:
        for chunk in r.iter_content(chunk_size=chunk_size):
            fd.write(chunk)

    with zipfile.ZipFile(file_path, 'r') as zip_ref:
        file_path = zip_ref.infolist()[0].filename
        zip_ref.extractall(dir)

    file_path = dir + file_path

    # flist = []
    for chunk in pd.read_fwf(file_path, chunksize=chunk_size):
        for year, df in chunk.groupby(res):
            fname = "{}-{}.csv".format(dir + file_path.split("/")[-1].split(".")[0], year)
            if os.path.isfile(fname):
                df.to_csv(fname, mode="a", index=False, header=False)
            else:
                df.to_csv(fname, index=False)
            # flist.append(fname)

    return True


if __name__ == "__main__":
    qindenton_dl('./data01/', res='Year')
`

**Comment by rweigel** [comment]
Commit code from travs_ci_testing to master and then close.

**Comment by rweigel** [comment]
Closed by 994362ec8851e29d6f218cd6fb8530087995b382
